apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
  — rolearn: arn:aws:iam::xxx:role/my-ec2-instance-role-eks-nodes
  username: serviceRole
  groups:
  — system:masters